{% set version = "0.6.4" %}
{% set python_min = python_min | default("3.9") %}

package:
  name: dparse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dparse/dparse-{{ version }}.tar.gz
  sha256: 90b29c39e3edc36c6284c82c4132648eaf28a01863eb3c231c2512196132201a

build:
  number: 0
  noarch: python
  script_env:
    # for `pipenv`: doesn't like `azure`
    - CI=true
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - packaging
    - python >={{ python_min }}
    - tomli

test:
  source_files:
    - tests
    - python {{ python_min }}
  requires:
    - coverage
    - pip
    - pipenv
    - poetry
    - pytest
    - pyyaml
  imports:
    - dparse
  commands:
    - pip check
    - coverage run --source dparse --branch -m pytest -vv --tb=long --color=yes
    - coverager report --show-missing --skip-covered --fail-under=85

about:
  home: https://github.com/pyupio/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files
  dev_url: https://github.com/pyupio/dparse

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
