{% set version = "0.6.4" %}

package:
  name: dparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dparse/dparse-{{ version }}.tar.gz
  sha256: 90b29c39e3edc36c6284c82c4132648eaf28a01863eb3c231c2512196132201a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  script_env:
    # for `pipenv`: doesn't like `azure`
    - CI=true

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - python >=3.6
    - pyyaml
    - tomli

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - pipenv
  imports:
    - dparse
  commands:
    - pip check
    - pytest -vv --cov dparse --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=85

about:
  home: https://github.com/pyupio/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files
  dev_url: https://github.com/pyupio/dparse

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
