{% set version = "0.6.3" %}

package:
  name: dparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dparse/dparse-{{ version }}.tar.gz
  sha256: 27bb8b4bcaefec3997697ba3f6e06b2447200ba273c0b085c3d012a04571b528

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  script_env:
    # for `pipenv`: doesn't like `azure`
    - CI=true

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - packaging
    - python >=3.5
    - pyyaml
    - toml

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pipenv
  imports:
    - dparse
  commands:
    - python -m pip check
    - pytest -vv

about:
  home: https://github.com/pyupio/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files
  dev_url: https://github.com/pyupio/dparse

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
