{% set version = "0.6.4b0" %}

package:
  name: dparse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dparse/dparse-{{ version }}.tar.gz
  sha256: f8d49b41a527f3d16a269f854e6665245b325e50e41d2c213810cb984553e5c8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python >=3.6
  run:
    - packaging
    - python >=3.6
    - tomli

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest-cov
    - pipenv
    - pyyaml
    - poetry
  imports:
    - dparse
  commands:
    - pip check
    - pytest -vv --cov dparse --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=85

about:
  home: https://github.com/pyupio/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files
  dev_url: https://github.com/pyupio/dparse

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
