{% set name = "dparse" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db349e53f6d03c8ee80606c49b35f515ed2ab287a8e1579e2b4bdf52b12b1530

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - packaging
    - python
    - pyyaml
    - six

test:
  imports:
    - dparse

about:
  home: https://github.com/jayfk/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files
  dev_url: https://github.com/jayfk/dparse

extra:
  recipe-maintainers:
    - jkornblum
