{% set version = "0.6.4" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set python_min = python_min | default("3.9") %}

package:
  name: dparse
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dparse/dparse-{{ version }}.tar.gz
  sha256: 90b29c39e3edc36c6284c82c4132648eaf28a01863eb3c231c2512196132201a

build:
  number: 0
  noarch: python
  script_env:
    # for `pipenv`: doesn't like `azure`
    - CI=true
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - packaging
    - python >={{ python_min }}
    - tomli

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - dparse
  commands:
    - pip check

outputs:
  - name: dparse

  - name: dparse-with-conda
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("dparse", max_pin="x.x.x") }}
        - pyyaml
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: dparse-with-pipenv
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("dparse", max_pin="x.x.x") }}
        - pipenv
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: dparse-with-poetry
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("dparse", max_pin="x.x.x") }}
        - poetry
    test:
      requires:
        - pip
      commands:
        - pip check

  - name: dparse-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("dparse-with-conda", max_pin="x.x.x") }}
        - {{ pin_subpackage("dparse-with-pipenv", max_pin="x.x.x") }}
        - {{ pin_subpackage("dparse-with-poetry", max_pin="x.x.x") }}
        - {{ pin_subpackage("dparse", max_pin="x.x.x") }}
    test:
      source_files:
        - tests
        - pyproject.toml
      requires:
        - pip
        - pytest-cov
      imports:
        - dparse
      commands:
        - pip check
        - pytest -vv --tb=long --color=yes --cov=dparse --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=78

about:
  home: https://github.com/pyupio/dparse
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parser for Python dependency files

extra:
  feedstock-name: dparse
  recipe-maintainers:
    - jkornblum
    - bollwyvl
